CREATE TABLE user_role_assignments (
    user_role_assignment_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    role_id BIGINT NOT NULL,
    granted_by UUID,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    revoked_at TIMESTAMPTZ,
    revoked_by UUID,
    revoke_reason TEXT,
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    FOREIGN KEY (role_id) REFERENCES roles(role_id),
    FOREIGN KEY (granted_by) REFERENCES users(user_id),
    FOREIGN KEY (revoked_by) REFERENCES users(user_id),
    CHECK (expires_at IS NULL OR expires_at > granted_at),
    CHECK ((is_active = TRUE AND revoked_at IS NULL) OR is_active = FALSE)
);

CREATE UNIQUE INDEX uq_active_secondary_role
ON user_role_assignments(user_id, role_id)
WHERE is_active = TRUE;

CREATE INDEX idx_user_role_assignments_user_id ON user_role_assignments(user_id);
CREATE INDEX idx_user_role_assignments_role_id ON user_role_assignments(role_id);

CREATE TABLE user_sessions (
    session_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    token_hash VARCHAR(255) NOT NULL UNIQUE,
    client_id VARCHAR(100),
    ip_address INET,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_activity_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    revoked_reason VARCHAR(255),
    FOREIGN KEY (user_id) REFERENCES users(user_id),
    CHECK (expires_at > created_at)
);

CREATE INDEX idx_sessions_user_active
ON user_sessions(user_id, expires_at)
WHERE revoked_at IS NULL;

CREATE TABLE login_history (
    login_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    attempted_username VARCHAR(50) NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address INET,
    client_id VARCHAR(100),
    success BOOLEAN NOT NULL,
    failure_reason VARCHAR(100),
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE INDEX idx_login_history_user_id ON login_history(user_id);
CREATE INDEX idx_login_history_occurred_at ON login_history(occurred_at);

CREATE TABLE staff_profiles (
    user_id UUID PRIMARY KEY,
    is_technician BOOLEAN NOT NULL DEFAULT FALSE,
    display_name VARCHAR(150),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);
