CREATE TABLE audit_logs (
    audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(60) NOT NULL,
    entity_id VARCHAR(100) NOT NULL,
    action_code VARCHAR(80) NOT NULL,
    actor_type VARCHAR(20) NOT NULL DEFAULT 'USER',
    actor_user_id UUID,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    changed_fields JSONB,
    ip_address INET,
    client_id VARCHAR(100),
    correlation_id VARCHAR(100),
    CHECK (actor_type IN ('USER','SYSTEM')),
    CHECK (
        (actor_type = 'USER' AND actor_user_id IS NOT NULL)
        OR actor_type = 'SYSTEM'
    ),
    FOREIGN KEY (actor_user_id) REFERENCES users(user_id)
);

CREATE INDEX idx_audit_logs_entity_occurred_at ON audit_logs(entity_type, entity_id, occurred_at DESC);
CREATE INDEX idx_audit_logs_action_occurred_at ON audit_logs(action_code, occurred_at DESC);
CREATE INDEX idx_audit_logs_actor_occurred_at ON audit_logs(actor_user_id, occurred_at DESC);
CREATE INDEX idx_audit_logs_correlation_id ON audit_logs(correlation_id);

CREATE TABLE role_change_audit (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES users(user_id) ON DELETE SET NULL,
    role_id BIGINT REFERENCES roles(role_id) ON DELETE SET NULL,
    grant_id UUID,
    action VARCHAR(32) NOT NULL,
    actor_user_id UUID REFERENCES users(user_id) ON DELETE SET NULL,
    details JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_role_change_audit_user_id ON role_change_audit(user_id);
