CREATE TABLE product_categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    parent_id BIGINT,
    description VARCHAR(255),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_product_categories_parent FOREIGN KEY (parent_id) REFERENCES product_categories(category_id),
    CONSTRAINT ck_product_categories_not_self CHECK (parent_id IS NULL OR parent_id <> category_id)
);

CREATE INDEX idx_product_categories_parent ON product_categories(parent_id);
CREATE INDEX idx_product_categories_active ON product_categories(is_active);

CREATE TABLE products (
    product_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sku VARCHAR(20) NOT NULL,
    barcode VARCHAR(50),
    name VARCHAR(200) NOT NULL,
    description TEXT,
    category_id BIGINT NOT NULL,
    uom_id BIGINT NOT NULL,
    product_type VARCHAR(20) NOT NULL DEFAULT 'INVENTORY',
    tax_category VARCHAR(20) NOT NULL DEFAULT 'STANDARD',
    cost_price NUMERIC(15,2) NOT NULL DEFAULT 0,
    selling_price NUMERIC(15,2) NOT NULL,
    wholesale_price NUMERIC(15,2),
    reorder_point NUMERIC(15,3) NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    image_path VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_products_sku UNIQUE (sku),
    CONSTRAINT uq_products_barcode UNIQUE (barcode),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES product_categories(category_id),
    CONSTRAINT fk_products_uom FOREIGN KEY (uom_id) REFERENCES uom(uom_id),
    CONSTRAINT ck_products_type CHECK (product_type IN ('INVENTORY','SERVICE')),
    CONSTRAINT ck_products_tax CHECK (tax_category IN ('STANDARD','EXEMPT','ZERO_RATED')),
    CONSTRAINT ck_products_cost CHECK (cost_price >= 0),
    CONSTRAINT ck_products_selling CHECK (selling_price >= 0),
    CONSTRAINT ck_products_wholesale CHECK (wholesale_price IS NULL OR wholesale_price >= 0),
    CONSTRAINT ck_products_reorder CHECK (reorder_point >= 0)
);

CREATE INDEX idx_products_name_trgm ON products USING gin (lower(name) gin_trgm_ops);
CREATE INDEX idx_products_sku_lookup ON products(sku);
CREATE INDEX idx_products_barcode_lookup ON products(barcode) WHERE barcode IS NOT NULL;
CREATE INDEX idx_products_category_active ON products(category_id, is_active);
CREATE INDEX idx_products_type_active ON products(product_type, is_active);

CREATE TABLE service_definitions (
    service_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    service_code VARCHAR(20) NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    category VARCHAR(100),
    base_price NUMERIC(15,2) NOT NULL DEFAULT 0,
    estimated_duration_minutes INTEGER NOT NULL,
    requires_estimate BOOLEAN NOT NULL DEFAULT FALSE,
    warranty_days INTEGER NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_service_definitions_code UNIQUE (service_code),
    CONSTRAINT ck_services_base_price CHECK (base_price >= 0),
    CONSTRAINT ck_services_duration CHECK (estimated_duration_minutes > 0),
    CONSTRAINT ck_services_warranty CHECK (warranty_days >= 0)
);

CREATE INDEX idx_services_name_trgm ON service_definitions USING gin (lower(name) gin_trgm_ops);
CREATE INDEX idx_services_category_active ON service_definitions(category, is_active);

CREATE TABLE suppliers (
    supplier_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    supplier_code VARCHAR(20) NOT NULL,
    name VARCHAR(200) NOT NULL,
    contact_person VARCHAR(150),
    address TEXT,
    phone VARCHAR(20),
    email VARCHAR(150),
    tin_number VARCHAR(30),
    payment_terms VARCHAR(255),
    opening_balance NUMERIC(15,2) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_suppliers_code UNIQUE (supplier_code),
    CONSTRAINT ck_suppliers_opening_balance CHECK (opening_balance >= 0),
    CONSTRAINT ck_suppliers_status CHECK (status IN ('ACTIVE','INACTIVE'))
);

CREATE INDEX idx_suppliers_name_trgm ON suppliers USING gin (lower(name) gin_trgm_ops);
CREATE INDEX idx_suppliers_status ON suppliers(status);

INSERT INTO permissions (permission_code, module, action, description)
VALUES
    ('product.view_cost', 'product', 'view_cost', 'View product cost price'),
    ('supplier.create', 'supplier', 'create', 'Create suppliers'),
    ('supplier.read', 'supplier', 'read', 'Read suppliers'),
    ('supplier.update', 'supplier', 'update', 'Update suppliers'),
    ('supplier.deactivate', 'supplier', 'deactivate', 'Deactivate suppliers')
ON CONFLICT (permission_code) DO UPDATE SET
    module = EXCLUDED.module,
    action = EXCLUDED.action,
    description = EXCLUDED.description;

INSERT INTO role_permissions (role_id, permission_code)
SELECT r.role_id, p.permission_code
FROM roles r
CROSS JOIN permissions p
WHERE r.role_name = 'SUPER_ADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_code)
SELECT r.role_id, p.permission_code
FROM roles r
JOIN permissions p ON p.permission_code IN (
    'product.view_cost', 'supplier.create', 'supplier.read', 'supplier.update', 'supplier.deactivate'
)
WHERE r.role_name IN ('OWNER', 'MANAGER')
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_code)
SELECT r.role_id, p.permission_code
FROM roles r
JOIN permissions p ON p.permission_code IN ('product.view_cost', 'supplier.read')
WHERE r.role_name IN ('ACCOUNTANT', 'AUDITOR')
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_code)
SELECT r.role_id, p.permission_code
FROM roles r
JOIN permissions p ON p.permission_code IN ('supplier.create', 'supplier.read', 'supplier.update')
WHERE r.role_name = 'STORE_KEEPER'
ON CONFLICT DO NOTHING;
