-- Phase 6 / Week 16 (DevelopmentPlan.md Week 16, DatabaseDesign.md §55): brands and dynamic
-- per-category attributes. Purely additive — no existing table's meaning changes.

CREATE TABLE brands (
    brand_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500),
    logo_path VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT uq_brands_name UNIQUE (name)
);

CREATE INDEX idx_brands_active ON brands(is_active);

CREATE TABLE attributes (
    attribute_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    data_type VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_attributes_name UNIQUE (name),
    CONSTRAINT ck_attributes_data_type CHECK (data_type IN ('TEXT','NUMBER','BOOLEAN','ENUM'))
);

CREATE TABLE attribute_values (
    attribute_value_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribute_id BIGINT NOT NULL,
    value VARCHAR(200) NOT NULL,
    CONSTRAINT uq_attribute_values UNIQUE (attribute_id, value),
    CONSTRAINT fk_attribute_values_attribute FOREIGN KEY (attribute_id) REFERENCES attributes(attribute_id)
);

CREATE INDEX idx_attribute_values_attribute ON attribute_values(attribute_id);

CREATE TABLE category_attributes (
    category_attribute_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    attribute_id BIGINT NOT NULL,
    is_required BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_category_attributes UNIQUE (category_id, attribute_id),
    CONSTRAINT fk_category_attributes_category FOREIGN KEY (category_id) REFERENCES product_categories(category_id),
    CONSTRAINT fk_category_attributes_attribute FOREIGN KEY (attribute_id) REFERENCES attributes(attribute_id)
);

CREATE INDEX idx_category_attributes_category ON category_attributes(category_id);
CREATE INDEX idx_category_attributes_attribute ON category_attributes(attribute_id);

-- products.brand_id (DatabaseDesign.md §55.1): nullable — a product without a brand remains
-- valid (MVP.md §4.8).
ALTER TABLE products ADD COLUMN brand_id BIGINT REFERENCES brands(brand_id);
CREATE INDEX idx_products_brand ON products(brand_id) WHERE brand_id IS NOT NULL;

INSERT INTO permissions (permission_code, module, action, description)
VALUES
    ('product.brand.read', 'product', 'brand.read', 'Read brands'),
    ('product.brand.create', 'product', 'brand.create', 'Create brands'),
    ('product.brand.update', 'product', 'brand.update', 'Update brands'),
    ('product.attribute.read', 'product', 'attribute.read', 'Read attributes and category assignments'),
    ('product.attribute.create', 'product', 'attribute.create', 'Create attributes and attribute values'),
    ('product.attribute.update', 'product', 'attribute.update', 'Update attributes and category assignments')
ON CONFLICT (permission_code) DO UPDATE SET
    module = EXCLUDED.module,
    action = EXCLUDED.action,
    description = EXCLUDED.description;

-- SUPER_ADMIN already receives every permission via V009's CROSS JOIN.
INSERT INTO role_permissions (role_id, permission_code)
SELECT r.role_id, p.permission_code
FROM roles r
CROSS JOIN permissions p
WHERE r.role_name = 'SUPER_ADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_code)
SELECT r.role_id, p.permission_code
FROM roles r
JOIN permissions p ON p.permission_code IN (
    'product.brand.read', 'product.brand.create', 'product.brand.update',
    'product.attribute.read', 'product.attribute.create', 'product.attribute.update'
)
WHERE r.role_name IN ('OWNER', 'MANAGER')
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_code)
SELECT r.role_id, p.permission_code
FROM roles r
JOIN permissions p ON p.permission_code IN ('product.brand.read', 'product.attribute.read')
WHERE r.role_name IN ('ACCOUNTANT', 'AUDITOR', 'STORE_KEEPER', 'CASHIER', 'SERVICE_OFFICER')
ON CONFLICT DO NOTHING;
