package com.bizco.common.api;

public enum ApiErrorCode {
    VALIDATION_FAILED("VALIDATION_FAILED"),
    AUTH_INVALID_CREDENTIALS("AUTH_INVALID_CREDENTIALS"),
    AUTH_ACCOUNT_LOCKED("AUTH_ACCOUNT_LOCKED"),
    AUTH_ACCOUNT_INACTIVE("AUTH_ACCOUNT_INACTIVE"),
    AUTH_CONCURRENT_SESSION_LIMIT("AUTH_CONCURRENT_SESSION_LIMIT"),
    AUTH_SESSION_INVALID("AUTH_SESSION_INVALID"),
    AUTH_SESSION_EXPIRED("AUTH_SESSION_EXPIRED"),
    AUTH_PERMISSION_DENIED("AUTH_PERMISSION_DENIED"),
    CONCURRENT_MODIFICATION("CONCURRENT_MODIFICATION"),
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND"),
    IDEMPOTENCY_CONFLICT("IDEMPOTENCY_CONFLICT"),
    DOMAIN_RULE_REJECTED("DOMAIN_RULE_REJECTED"),
    SYSTEM_MAINTENANCE("SYSTEM_MAINTENANCE"),
    INTERNAL_ERROR("INTERNAL_ERROR"),
    IDENTITY_ERROR("IDENTITY_ERROR");

    private final String code;

    ApiErrorCode(final String code) {
        this.code = code;
    }

    public String code() {
        return code;
    }
}
