package com.bizco.common.api;

public enum ApiErrorCode {
    VALIDATION_FAILED("VALIDATION_FAILED"),
    AUTH_INVALID_CREDENTIALS("AUTH_INVALID_CREDENTIALS"),
    AUTH_ACCOUNT_LOCKED("AUTH_ACCOUNT_LOCKED"),
    AUTH_ACCOUNT_INACTIVE("AUTH_ACCOUNT_INACTIVE"),
    AUTH_CONCURRENT_SESSION_LIMIT("AUTH_CONCURRENT_SESSION_LIMIT"),
    AUTH_SESSION_INVALID("AUTH_SESSION_INVALID"),
    AUTH_SESSION_EXPIRED("AUTH_SESSION_EXPIRED"),
    AUTH_PERMISSION_DENIED("AUTH_PERMISSION_DENIED"),
    CONCURRENT_MODIFICATION("CONCURRENT_MODIFICATION"),
    RESOURCE_NOT_FOUND("RESOURCE_NOT_FOUND"),
    CUSTOMER_NOT_FOUND("CUSTOMER_NOT_FOUND"),
    CUSTOMER_CODE_DUPLICATE("CUSTOMER_CODE_DUPLICATE"),
    CUSTOMER_ANONYMIZATION_BLOCKED("CUSTOMER_ANONYMIZATION_BLOCKED"),
    CUSTOMER_CREDIT_LIMIT_EXCEEDED("CUSTOMER_CREDIT_LIMIT_EXCEEDED"),
    PRODUCT_NOT_FOUND("PRODUCT_NOT_FOUND"),
    PRODUCT_SKU_DUPLICATE("PRODUCT_SKU_DUPLICATE"),
    PRODUCT_BARCODE_DUPLICATE("PRODUCT_BARCODE_DUPLICATE"),
    PRODUCT_INACTIVE("PRODUCT_INACTIVE"),
    CATEGORY_NOT_FOUND("CATEGORY_NOT_FOUND"),
    CATEGORY_IN_USE("CATEGORY_IN_USE"),
    CATEGORY_CYCLE("CATEGORY_CYCLE"),
    UOM_NOT_FOUND("UOM_NOT_FOUND"),
    SERVICE_NOT_FOUND("SERVICE_NOT_FOUND"),
    SERVICE_CODE_DUPLICATE("SERVICE_CODE_DUPLICATE"),
    SUPPLIER_NOT_FOUND("SUPPLIER_NOT_FOUND"),
    SUPPLIER_CODE_DUPLICATE("SUPPLIER_CODE_DUPLICATE"),
    INVOICE_NOT_FOUND("INVOICE_NOT_FOUND"),
    INVOICE_NOT_DRAFT("INVOICE_NOT_DRAFT"),
    INVOICE_LINE_NOT_FOUND("INVOICE_LINE_NOT_FOUND"),
    INVOICE_DISCOUNT_APPROVAL_REQUIRED("INVOICE_DISCOUNT_APPROVAL_REQUIRED"),
    INVOICE_BELOW_COST_APPROVAL_REQUIRED("INVOICE_BELOW_COST_APPROVAL_REQUIRED"),
    INVOICE_CREDIT_CUSTOMER_REQUIRED("INVOICE_CREDIT_CUSTOMER_REQUIRED"),
    INVOICE_PAYMENT_REQUIRED("INVOICE_PAYMENT_REQUIRED"),
    CUSTOMER_CREDIT_BLOCKED_BY_AGING("CUSTOMER_CREDIT_BLOCKED_BY_AGING"),
    CUSTOMER_SALES_BLOCKED("CUSTOMER_SALES_BLOCKED"),
    IDEMPOTENCY_CONFLICT("IDEMPOTENCY_CONFLICT"),
    DOMAIN_RULE_REJECTED("DOMAIN_RULE_REJECTED"),
    SYSTEM_MAINTENANCE("SYSTEM_MAINTENANCE"),
    INTERNAL_ERROR("INTERNAL_ERROR"),
    IDENTITY_ERROR("IDENTITY_ERROR");

    private final String code;

    ApiErrorCode(final String code) {
        this.code = code;
    }

    public String code() {
        return code;
    }
}
